### ISSUE TITLE
Getting error while try up your nvim build.

### ISSUE THREAD

**Issue by thyeun** [folke/dot#16]
Getting several error from the below images, it is because i done a mistake or any extra change needed, to make it work.

![Screenshot_2023-06-04-23-40-03_21456](https://github.com/folke/dot/assets/1939446/f267c7b8-f72d-42c0-a819-689ef6b5ba30)

![Screenshot_2023-06-04-23-40-13_14794](https://github.com/folke/dot/assets/1939446/d9df5ce9-ce8e-48b3-bfd0-a34ca4bbcdf6)

![Screenshot_2023-06-04-23-40-24_19710](https://github.com/folke/dot/assets/1939446/e9e4ca31-044a-4bdb-b0fe-6e956f897569)

![Screenshot_2023-06-04-23-40-33_9265](https://github.com/folke/dot/assets/1939446/1d98978d-295d-4407-9692-65bcd80e2726)

**Comment by folke** [comment]
You should not use this config. Use LazyVim instead, which is 99% the same as this config.
