### ISSUE TITLE
Accidentally leaked API key

### ISSUE THREAD

**Issue by MoritzBoehme** [folke/dot#18]
Hey, I was just looking through your dotfiles and stumbled upon this line.
https://github.com/folke/dot/blob/d2bf2a937053ecb698b7a62d779b349a1edfa6c1/nvim/lua/plugins/coding.lua#L5
Apparently `hfcc.nvim` now also supports setting the key using environment variables or by using the hugginface cli. See [here](https://github.com/huggingface/hfcc.nvim#install).
This change was ironically introduced 2 days after your commit, which added the plugin to your config.

**Comment by folke** [comment]
Fixed, thanks for letting me know!
