### ISSUE TITLE
How did you set up your outline's postition?

### ISSUE THREAD

**Issue by ogios** [folke/dot#19]
sorry i'm new to neovim, and i've searched through your nvim config but didn't find where is it set and encoutered error when derectly open nvim with your config.
![image](https://github.com/folke/dot/assets/96933655/66897785-290c-4882-97d6-f034709be9ea)

**Comment by folke** [comment]
Yeah, you should not just use my config. I did not make it to be used like that.
Just use LazyVim.

The outline positioning etc is done by `edgy.nvim`
