### ISSUE TITLE
bat colorscheme not applying

### ISSUE THREAD

**Issue by harshv5094** [folke/dot#23]
I'm using @folke bat config in my config, but I'm unable to use config colors in bat file
![image](https://github.com/folke/dot/assets/51878195/b8cde809-0ec9-4b4d-8587-11c36e3fed5f)

I'm so confused right now.

**Comment by folke** [comment]
Please don't open issues in my dot files...

Anyway, you need to run `bat cache --build` first.

If that doesn't work, then you'll have to figure it out yourself.
