### ISSUE TITLE
nVim magic

### ISSUE THREAD

**Issue by savchenko** [folke/dot#3]
Hi,

I wonder if you plan do jam a write-up on your setup:
![WTF?!](https://user-images.githubusercontent.com/292349/118454007-b7d8c900-b6ac-11eb-8263-015a8d929644.png)

Indentline that works over empty lines with dynamic highlight is especially interesting.

Thanks!

**Comment by folke** [comment]
That indentline is from this plugin: https://github.com/lukas-reineke/indent-blankline.nvim
